blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/SharanRP/COC_Landing/discussions
    about: Please ask and answer questions here.
  - name: Documentation Issue
    url: https://github.com/SharanRP/COC_Landing/issues/new?labels=documentation
    about: Report issues with documentation here.

templates:
  - name: Bug Report
    about: Create a report to help us improve
    template: bug_report.md
    title: "[BUG] "
    labels: [bug]
    
  - name: Feature Request
    about: Suggest an idea for this project
    template: feature_request.md
    title: "[FEATURE] "
    labels: [enhancement] 